name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set working directory
        run: cd HanabiTracker

      - name: Set up Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'HanabiTracker/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build --deploy-url /HanabiTracker/

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: /HanabiTracker/dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
